from methods.base import BaseRouter
from methods.mlp import MLPRouter
from methods.Avengers import Avengers
from methods.AvengersPro import AvengersPro
from methods.MIRT import MIRT
from methods.NIRT import NIRT
from methods.GraphRouter import GraphRouter
from methods.RouterDC import RouterDC
from methods.HybridLLM import HybridLLM
from methods.Eagle import Eagle
from methods.EmbedLLM import EmbedLLM
from methods.kNNRouter import kNNRouter
from methods.SVMRouter import SVMRouter
from methods.RouteLLM import RouteLLM_SWRanking,RouteLLM_MF,RouteLLM_BERT
from methods.OmniRouter import OmniRouter
from methods.CausalRouter import RMSoftmax,RMClassification,RMInterval
from methods.EquiRouter import EquiRouter
from methods.oracle import OracleRouter